### ISSUE TITLE
Possible to setup more than one

### ISSUE THREAD

**Issue by Eonasdan** [xabikos/EfMultitenant#3]
Thanks for your source and tutorial.

I'm currently working on a project that basically requires multi-multi-tenancy. Scary, I know.

We would like to be able to use your code to setup two annotations for two different columns.

In some cases, only one attribute will be present, but when the second attribute **is** there, both will be present.

Example:
Company = Level 1 <- allowing for different Stores
&nbsp;&nbsp;&nbsp;&nbsp;|-> Store = Level 2 <- Store will always be part of company
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|-> Inventory = Level 3 <- Inventory will always be part of Store, and thereby Company

I'm having some trouble getting this to work together.

**Comment by xabikos** [comment]
Theoretically speaking I don't see a reason why you couldn't do that. But if you could set up a small example application to make it more concrete maybe I could give some help. What the code here does is getting an attribute and manipulates the sql queries in the object representations. So do it for more than one annotations should be fine.

**Comment by Eonasdan** [comment]
Sorry for the really long delay. I did finally get this to work about a month or so ago and finally got around to writing an article about.

http://www.eonasdan.com/home/two-level-multi-tenant

Thanks for the primer!
